In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "State": ["Karnataka", "Tamil Nadu", "Kerala", "Delhi", "Karnataka"],
    "Population": [67562686, 72147030, np.nan, 16787941, 67562686],
    "Area": [191791, 130058, 38863, 1484, 191791],
    "Region": ["South", "South", "South", "North", "South"]
}

df = pd.DataFrame(data)

df.to_csv("india_states.csv", index=False)

In [3]:
# Load the dataset
df = pd.read_csv("india_states.csv")

In [4]:
# Display first 10 rows
df.head(10)

        State  Population    Area Region
0   Karnataka  67562686.0  191791  South
1  Tamil Nadu  72147030.0  130058  South
2      Kerala         NaN   38863  South
3       Delhi  16787941.0    1484  North
4   Karnataka  67562686.0  191791  South

In [6]:
# Display rows and columns
print(df.shape)

(5, 4)

In [7]:
# Display data types
print(df.dtypes)

State          object
Population    float64
Area            int64
Region         object
dtype: object

In [8]:
# Statistical summary
df.describe()

         Population           Area
count  4.000000e+00       5.000000
mean   5.601509e+07  110797.400000
std    2.624057e+07   87485.533829
min    1.678794e+07    1484.000000
25%    5.486900e+07   38863.000000
50%    6.756269e+07  130058.000000
75%    6.870877e+07  191791.000000
max    7.214703e+07  191791.000000

In [9]:
# Count missing values
print(df.isnull().sum())

State         0
Population    1
Area          0
Region        0
dtype: int64

In [10]:
# Replace missing values with column mean
df["Population"].fillna(df["Population"].mean(), inplace=True)

/tmp/ipykernel_1615/3046558568.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Population"].fillna(df["Population"].mean(), inplace=True)

In [13]:
df.head()

        State   Population    Area Region
0   Karnataka  67562686.00  191791  South
1  Tamil Nadu  72147030.00  130058  South
2      Kerala  56015085.75   38863  South
3       Delhi  16787941.00    1484  North

In [14]:
df.head()

        State   Population    Area Region
0   Karnataka  67562686.00  191791  South
1  Tamil Nadu  72147030.00  130058  South
2      Kerala  56015085.75   38863  South
3       Delhi  16787941.00    1484  North

In [15]:
df.to_csv("cleaned_india_states.csv", index=False)

In [16]:
!pip install pyarrow

df.to_parquet("cleaned_india_states.parquet", index=False)

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [11]:
# Remove duplicate records
df = df.drop_duplicates()

In [12]:
print(df.isnull().sum())

print(df.duplicated().sum())

State         0
Population    0
Area          0
Region        0
dtype: int64
0